apiVersion: v1
kind: Service
annotations: 
  cloud.google.com/load-balancer-type: "Internal"
  external-dns.alpha.kubernetes.io/hostname: {{ .Values.fqdn }}
metadata:
  name: {{ include "k8s-private-api.fullname" . }}
  labels:
{{ include "k8s-private-api.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "k8s-private-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
